[2024-11-05T12:59:42.877+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:59:43.228+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:59:43.425+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:59:43.426+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-05T12:59:43.469+0000] {taskinstance.py:2888} INFO - Executing <Task(DbtSeedBashOperator): transform.production.seed.adventureworks.product> on 2024-11-05 12:51:34.487256+00:00
[2024-11-05T12:59:43.499+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T12:59:43.501+0000] {standard_task_runner.py:72} INFO - Started process 564 to run task
[2024-11-05T12:59:43.503+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow_orchestration', 'transform.production.seed.adventureworks.product', 'manual__2024-11-05T12:51:34.487256+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/dbt_orchestration.py', '--cfg-path', '/tmp/tmpyump2a9g']
[2024-11-05T12:59:43.506+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask transform.production.seed.adventureworks.product
[2024-11-05T12:59:43.825+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product manual__2024-11-05T12:51:34.487256+00:00 [running]> on host e36b82c08833
[2024-11-05T12:59:44.520+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow_orchestration' AIRFLOW_CTX_TASK_ID='transform.production.seed.adventureworks.product' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:51:34.487256+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T12:51:34.487256+00:00'
[2024-11-05T12:59:44.524+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:59:45.780+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T12:59:45.781+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-write-json seed --project-dir /opt/dbt --profiles-dir /opt/dbt --target dev --select product']
[2024-11-05T12:59:45.891+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:00:06.506+0000] {subprocess.py:93} INFO - [0m13:00:06  Running with dbt=1.8.2
[2024-11-05T13:00:06.544+0000] {subprocess.py:93} INFO - [0m13:00:06  Encountered an error:
[2024-11-05T13:00:06.545+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-05T13:00:06.545+0000] {subprocess.py:93} INFO -   The profile 'adventureworks' does not have a target named 'dev'. The valid target names for this profile are:
[2024-11-05T13:00:06.546+0000] {subprocess.py:93} INFO -    - postgres
[2024-11-05T13:00:10.010+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T13:00:10.030+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:00:10.036+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_workflow_orchestration, task_id=transform.production.seed.adventureworks.product, run_id=manual__2024-11-05T12:51:34.487256+00:00, execution_date=20241105T125134, start_date=20241105T125943, end_date=20241105T130010
[2024-11-05T13:00:10.068+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:00:10.069+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 70 for task transform.production.seed.adventureworks.product (Bash command failed. The command returned a non-zero exit code 2.; 564)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:00:10.130+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T13:00:10.303+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:00:10.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
