[2024-11-05T13:16:31.984+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:16:32.014+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:16:32.040+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:16:32.040+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T13:16:32.062+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-04 00:00:00+00:00
[2024-11-05T13:16:32.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=864) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:16:32.074+0000] {standard_task_runner.py:72} INFO - Started process 868 to run task
[2024-11-05T13:16:32.075+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_project_dag', 'dbt_run', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dbt_orchestration.py', '--cfg-path', '/tmp/tmpwqq16mib']
[2024-11-05T13:16:32.077+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask dbt_run
[2024-11-05T13:16:32.148+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [running]> on host e36b82c08833
[2024-11-05T13:16:32.253+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_project_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T13:16:32.255+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:16:32.277+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:16:32.278+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && dbt run --profiles-dir /root/.dbt']
[2024-11-05T13:16:32.289+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:16:35.489+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-11-05T13:16:35.490+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-11-05T13:16:35.491+0000] {subprocess.py:93} INFO - 
[2024-11-05T13:16:35.492+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-11-05T13:16:35.790+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T13:16:35.805+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:16:35.818+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_project_dag, task_id=dbt_run, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T131632, end_date=20241105T131635
[2024-11-05T13:16:35.861+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:16:35.862+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 80 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 868)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:16:35.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T13:16:35.941+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:16:35.943+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-05T13:24:32.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:24:32.450+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:24:32.463+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:24:32.464+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T13:24:32.482+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-04 00:00:00+00:00
[2024-11-05T13:24:32.494+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1046) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:24:32.499+0000] {standard_task_runner.py:72} INFO - Started process 1047 to run task
[2024-11-05T13:24:32.501+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_project_dag', 'dbt_run', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dbt_project_dag.py', '--cfg-path', '/tmp/tmpcuvwonpm']
[2024-11-05T13:24:32.503+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask dbt_run
[2024-11-05T13:24:32.589+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [running]> on host e36b82c08833
[2024-11-05T13:24:32.742+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_project_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T13:24:32.743+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:24:32.761+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:24:32.762+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && dbt run --profiles-dir /root/.dbt']
[2024-11-05T13:24:32.772+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:24:35.861+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-11-05T13:24:35.862+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-11-05T13:24:35.862+0000] {subprocess.py:93} INFO - 
[2024-11-05T13:24:35.863+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-11-05T13:24:36.152+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T13:24:36.165+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:24:36.175+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_project_dag, task_id=dbt_run, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T132432, end_date=20241105T132436
[2024-11-05T13:24:36.194+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:24:36.195+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 87 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1047)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:24:36.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T13:24:36.250+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:24:36.252+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-05T13:41:49.262+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:41:49.287+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:41:49.299+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:41:49.300+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-05T13:41:49.317+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-04 00:00:00+00:00
[2024-11-05T13:41:49.323+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:41:49.324+0000] {standard_task_runner.py:72} INFO - Started process 272 to run task
[2024-11-05T13:41:49.325+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_project_dag', 'dbt_run', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dbt_project_dag.py', '--cfg-path', '/tmp/tmpzz705cmj']
[2024-11-05T13:41:49.326+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask dbt_run
[2024-11-05T13:41:49.382+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_project_dag.dbt_run scheduled__2024-11-04T00:00:00+00:00 [running]> on host bbd20199defe
[2024-11-05T13:41:49.524+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_project_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T13:41:49.525+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:41:49.555+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:41:49.556+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && dbt run ']
[2024-11-05T13:41:49.573+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:41:52.573+0000] {subprocess.py:93} INFO - [0m13:41:52  Running with dbt=1.8.2
[2024-11-05T13:41:52.938+0000] {subprocess.py:93} INFO - [0m13:41:52  Registered adapter: postgres=1.8.2
[2024-11-05T13:41:53.770+0000] {subprocess.py:93} INFO - [0m13:41:53  Found 8 models, 15 seeds, 42 data tests, 541 macros
[2024-11-05T13:41:53.781+0000] {subprocess.py:93} INFO - [0m13:41:53
[2024-11-05T13:41:54.092+0000] {subprocess.py:93} INFO - [0m13:41:54  Concurrency: 12 threads (target='postgres')
[2024-11-05T13:41:54.094+0000] {subprocess.py:93} INFO - [0m13:41:54
[2024-11-05T13:41:54.116+0000] {subprocess.py:93} INFO - [0m13:41:54  1 of 8 START sql table model marts.dim_address ................................. [RUN]
[2024-11-05T13:41:54.120+0000] {subprocess.py:93} INFO - [0m13:41:54  2 of 8 START sql table model marts.dim_credit_card ............................. [RUN]
[2024-11-05T13:41:54.138+0000] {subprocess.py:93} INFO - [0m13:41:54  3 of 8 START sql table model marts.dim_customer ................................ [RUN]
[2024-11-05T13:41:54.154+0000] {subprocess.py:93} INFO - [0m13:41:54  6 of 8 START sql table model marts.dim_product ................................. [RUN]
[2024-11-05T13:41:54.156+0000] {subprocess.py:93} INFO - [0m13:41:54  7 of 8 START sql table model marts.fct_sales ................................... [RUN]
[2024-11-05T13:41:54.179+0000] {subprocess.py:93} INFO - [0m13:41:54  4 of 8 START sql table model marts.dim_date .................................... [RUN]
[2024-11-05T13:41:54.182+0000] {subprocess.py:93} INFO - [0m13:41:54  5 of 8 START sql table model marts.dim_order_status ............................ [RUN]
[2024-11-05T13:41:54.929+0000] {subprocess.py:93} INFO - [0m13:41:54  5 of 8 OK created sql table model marts.dim_order_status ....................... [[32mSELECT 1[0m in 0.74s]
[2024-11-05T13:41:54.931+0000] {subprocess.py:93} INFO - [0m13:41:54  1 of 8 OK created sql table model marts.dim_address ............................ [[32mSELECT 1675[0m in 0.80s]
[2024-11-05T13:41:54.932+0000] {subprocess.py:93} INFO - [0m13:41:54  6 of 8 OK created sql table model marts.dim_product ............................ [[32mSELECT 504[0m in 0.73s]
[2024-11-05T13:41:54.949+0000] {subprocess.py:93} INFO - [0m13:41:54  4 of 8 OK created sql table model marts.dim_date ............................... [[32mSELECT 731[0m in 0.75s]
[2024-11-05T13:41:54.967+0000] {subprocess.py:93} INFO - [0m13:41:54  2 of 8 OK created sql table model marts.dim_credit_card ........................ [[32mSELECT 1316[0m in 0.79s]
[2024-11-05T13:41:54.978+0000] {subprocess.py:93} INFO - [0m13:41:54  7 of 8 OK created sql table model marts.fct_sales .............................. [[32mSELECT 5675[0m in 0.79s]
[2024-11-05T13:41:54.988+0000] {subprocess.py:93} INFO - [0m13:41:54  3 of 8 OK created sql table model marts.dim_customer ........................... [[32mSELECT 19820[0m in 0.79s]
[2024-11-05T13:41:54.993+0000] {subprocess.py:93} INFO - [0m13:41:54  8 of 8 START sql table model marts.obt_sales ................................... [RUN]
[2024-11-05T13:41:56.942+0000] {subprocess.py:93} INFO - [0m13:41:56  8 of 8 OK created sql table model marts.obt_sales .............................. [[32mSELECT 5675[0m in 1.95s]
[2024-11-05T13:41:56.974+0000] {subprocess.py:93} INFO - [0m13:41:56
[2024-11-05T13:41:56.975+0000] {subprocess.py:93} INFO - [0m13:41:56  Finished running 8 table models in 0 hours 0 minutes and 3.19 seconds (3.19s).
[2024-11-05T13:41:57.092+0000] {subprocess.py:93} INFO - [0m13:41:57
[2024-11-05T13:41:57.093+0000] {subprocess.py:93} INFO - [0m13:41:57  [32mCompleted successfully[0m
[2024-11-05T13:41:57.094+0000] {subprocess.py:93} INFO - [0m13:41:57
[2024-11-05T13:41:57.095+0000] {subprocess.py:93} INFO - [0m13:41:57  Done. PASS=8 WARN=0 ERROR=0 SKIP=0 TOTAL=8
[2024-11-05T13:41:58.604+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-05T13:41:58.651+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:41:58.651+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_project_dag, task_id=dbt_run, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T134149, end_date=20241105T134158
[2024-11-05T13:41:58.700+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:41:58.725+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:41:58.727+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
