[2024-11-05T12:54:04.470+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:54:04.602+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.sales.seed.adventureworks.customer manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:54:04.690+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.sales.seed.adventureworks.customer manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:54:04.691+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T12:54:04.889+0000] {taskinstance.py:2888} INFO - Executing <Task(DbtSeedBashOperator): transform.sales.seed.adventureworks.customer> on 2024-11-05 12:51:34.487256+00:00
[2024-11-05T12:54:04.919+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T12:54:04.922+0000] {standard_task_runner.py:72} INFO - Started process 337 to run task
[2024-11-05T12:54:04.937+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow_orchestration', 'transform.sales.seed.adventureworks.customer', 'manual__2024-11-05T12:51:34.487256+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dbt_orchestration.py', '--cfg-path', '/tmp/tmpxt50wx5x']
[2024-11-05T12:54:04.948+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask transform.sales.seed.adventureworks.customer
[2024-11-05T12:54:05.566+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow_orchestration.transform.sales.seed.adventureworks.customer manual__2024-11-05T12:51:34.487256+00:00 [running]> on host e36b82c08833
[2024-11-05T12:54:06.185+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow_orchestration' AIRFLOW_CTX_TASK_ID='transform.sales.seed.adventureworks.customer' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:51:34.487256+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T12:51:34.487256+00:00'
[2024-11-05T12:54:06.188+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:54:08.282+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T12:54:08.286+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-write-json seed --project-dir /opt/dbt --profiles-dir /opt/dbt --target dev --select customer']
[2024-11-05T12:54:08.333+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T12:54:27.313+0000] {subprocess.py:93} INFO - [0m12:54:27  Running with dbt=1.8.2
[2024-11-05T12:54:27.339+0000] {subprocess.py:93} INFO - [0m12:54:27  Encountered an error:
[2024-11-05T12:54:27.339+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-05T12:54:27.340+0000] {subprocess.py:93} INFO -   The profile 'adventureworks' does not have a target named 'dev'. The valid target names for this profile are:
[2024-11-05T12:54:27.340+0000] {subprocess.py:93} INFO -    - postgres
[2024-11-05T12:54:28.689+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T12:54:28.746+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T12:54:28.810+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_workflow_orchestration, task_id=transform.sales.seed.adventureworks.customer, run_id=manual__2024-11-05T12:51:34.487256+00:00, execution_date=20241105T125134, start_date=20241105T125404, end_date=20241105T125428
[2024-11-05T12:54:28.862+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T12:54:28.863+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task transform.sales.seed.adventureworks.customer (Bash command failed. The command returned a non-zero exit code 2.; 337)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T12:54:28.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T12:54:29.000+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T12:54:29.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
