[2024-11-05T13:46:32.641+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:46:32.677+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:46:30.653027+00:00 [queued]>
[2024-11-05T13:46:32.692+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:46:30.653027+00:00 [queued]>
[2024-11-05T13:46:32.693+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T13:46:32.723+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_docs_serve> on 2024-11-05 13:46:30.653027+00:00
[2024-11-05T13:46:32.732+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=417) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:46:32.740+0000] {standard_task_runner.py:72} INFO - Started process 418 to run task
[2024-11-05T13:46:32.738+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_docs_serve_dag', 'dbt_docs_serve', 'manual__2024-11-05T13:46:30.653027+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dbt_docs_serve_dag.py', '--cfg-path', '/tmp/tmp4cuy3d3q']
[2024-11-05T13:46:32.743+0000] {standard_task_runner.py:105} INFO - Job 102: Subtask dbt_docs_serve
[2024-11-05T13:46:32.834+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:46:30.653027+00:00 [running]> on host bbd20199defe
[2024-11-05T13:46:32.980+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_docs_serve_dag' AIRFLOW_CTX_TASK_ID='dbt_docs_serve' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T13:46:30.653027+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T13:46:30.653027+00:00'
[2024-11-05T13:46:32.981+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:46:33.020+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:46:33.022+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && nohup dbt docs serve --profiles-dir /root/.dbt --port 8001 &']
[2024-11-05T13:46:33.046+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:46:37.923+0000] {subprocess.py:93} INFO - Usage: dbt docs serve [OPTIONS]
[2024-11-05T13:46:37.923+0000] {subprocess.py:93} INFO - Try 'dbt docs serve -h' for help.
[2024-11-05T13:46:37.924+0000] {subprocess.py:93} INFO - 
[2024-11-05T13:46:37.925+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-11-05T13:46:38.378+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-05T13:46:38.447+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:46:38.448+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_docs_serve_dag, task_id=dbt_docs_serve, run_id=manual__2024-11-05T13:46:30.653027+00:00, execution_date=20241105T134630, start_date=20241105T134632, end_date=20241105T134638
[2024-11-05T13:46:38.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:46:38.564+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:46:38.567+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
