[2024-11-05T13:51:04.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:51:04.720+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:03.592246+00:00 [queued]>
[2024-11-05T13:51:04.739+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:03.592246+00:00 [queued]>
[2024-11-05T13:51:04.740+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T13:51:04.773+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_docs_serve> on 2024-11-05 13:51:03.592246+00:00
[2024-11-05T13:51:04.784+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:51:04.787+0000] {standard_task_runner.py:72} INFO - Started process 499 to run task
[2024-11-05T13:51:04.789+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_docs_serve_dag', 'dbt_docs_serve', 'manual__2024-11-05T13:51:03.592246+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dbt_docs_serve_dag.py', '--cfg-path', '/tmp/tmp909wxs8t']
[2024-11-05T13:51:04.791+0000] {standard_task_runner.py:105} INFO - Job 108: Subtask dbt_docs_serve
[2024-11-05T13:51:04.894+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:03.592246+00:00 [running]> on host bbd20199defe
[2024-11-05T13:51:05.040+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_docs_serve_dag' AIRFLOW_CTX_TASK_ID='dbt_docs_serve' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T13:51:03.592246+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T13:51:03.592246+00:00'
[2024-11-05T13:51:05.041+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:51:05.069+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:51:05.069+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && nohup dbt docs serve --profiles-dir /root/.dbt --port 8001 &']
[2024-11-05T13:51:05.087+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:51:08.328+0000] {subprocess.py:93} INFO - Usage: dbt docs serve [OPTIONS]
[2024-11-05T13:51:08.328+0000] {subprocess.py:93} INFO - Try 'dbt docs serve -h' for help.
[2024-11-05T13:51:08.329+0000] {subprocess.py:93} INFO - 
[2024-11-05T13:51:08.330+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-11-05T13:51:08.606+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-05T13:51:08.634+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:51:08.635+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_docs_serve_dag, task_id=dbt_docs_serve, run_id=manual__2024-11-05T13:51:03.592246+00:00, execution_date=20241105T135103, start_date=20241105T135104, end_date=20241105T135108
[2024-11-05T13:51:08.661+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:51:08.692+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:51:08.694+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
