[2024-11-05T12:51:58.463+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:51:59.198+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T12:51:59.312+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T12:51:59.314+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T12:51:59.603+0000] {taskinstance.py:2888} INFO - Executing <Task(DbtSeedBashOperator): transform.production.seed.adventureworks.product> on 2024-11-04 00:00:00+00:00
[2024-11-05T12:51:59.644+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T12:51:59.657+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2024-11-05T12:51:59.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow_orchestration', 'transform.production.seed.adventureworks.product', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dbt_orchestration.py', '--cfg-path', '/tmp/tmpaaa7ljdo']
[2024-11-05T12:51:59.677+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask transform.production.seed.adventureworks.product
[2024-11-05T12:52:00.168+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow_orchestration.transform.production.seed.adventureworks.product scheduled__2024-11-04T00:00:00+00:00 [running]> on host e36b82c08833
[2024-11-05T12:52:00.640+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow_orchestration' AIRFLOW_CTX_TASK_ID='transform.production.seed.adventureworks.product' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T12:52:00.691+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:52:00.999+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T12:52:35.397+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-write-json seed --project-dir /opt/dbt --profiles-dir /opt/dbt --target dev --select product']
[2024-11-05T12:52:35.531+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T12:52:38.108+0000] {job.py:229} INFO - Heartbeat recovered after 40.14 seconds
[2024-11-05T12:53:18.132+0000] {job.py:229} INFO - Heartbeat recovered after 34.55 seconds
[2024-11-05T12:53:41.157+0000] {subprocess.py:93} INFO - [0m12:53:41  Running with dbt=1.8.2
[2024-11-05T12:53:41.211+0000] {subprocess.py:93} INFO - [0m12:53:41  Encountered an error:
[2024-11-05T12:53:41.212+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-05T12:53:41.212+0000] {subprocess.py:93} INFO -   The profile 'adventureworks' does not have a target named 'dev'. The valid target names for this profile are:
[2024-11-05T12:53:41.260+0000] {subprocess.py:93} INFO -    - postgres
[2024-11-05T12:53:47.631+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T12:53:48.104+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T12:53:48.361+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_workflow_orchestration, task_id=transform.production.seed.adventureworks.product, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T125159, end_date=20241105T125348
[2024-11-05T12:53:54.670+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T12:53:54.670+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task transform.production.seed.adventureworks.product (Bash command failed. The command returned a non-zero exit code 2.; 268)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T12:53:54.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T12:53:55.040+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
