[2024-11-05T12:59:39.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T12:59:39.895+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.person.seed.adventureworks.address manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:59:40.041+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow_orchestration.transform.person.seed.adventureworks.address manual__2024-11-05T12:51:34.487256+00:00 [queued]>
[2024-11-05T12:59:40.067+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-05T12:59:40.300+0000] {taskinstance.py:2888} INFO - Executing <Task(DbtSeedBashOperator): transform.person.seed.adventureworks.address> on 2024-11-05 12:51:34.487256+00:00
[2024-11-05T12:59:40.393+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T12:59:40.416+0000] {standard_task_runner.py:72} INFO - Started process 553 to run task
[2024-11-05T12:59:40.407+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow_orchestration', 'transform.person.seed.adventureworks.address', 'manual__2024-11-05T12:51:34.487256+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dbt_orchestration.py', '--cfg-path', '/tmp/tmph0cjfkgl']
[2024-11-05T12:59:40.427+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask transform.person.seed.adventureworks.address
[2024-11-05T12:59:40.756+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow_orchestration.transform.person.seed.adventureworks.address manual__2024-11-05T12:51:34.487256+00:00 [running]> on host e36b82c08833
[2024-11-05T12:59:41.586+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow_orchestration' AIRFLOW_CTX_TASK_ID='transform.person.seed.adventureworks.address' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:51:34.487256+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T12:51:34.487256+00:00'
[2024-11-05T12:59:41.587+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T12:59:42.923+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T12:59:42.928+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt --no-write-json seed --project-dir /opt/dbt --profiles-dir /opt/dbt --target dev --select address']
[2024-11-05T12:59:42.977+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:00:01.257+0000] {subprocess.py:93} INFO - [0m13:00:01  Running with dbt=1.8.2
[2024-11-05T13:00:01.275+0000] {subprocess.py:93} INFO - [0m13:00:01  Encountered an error:
[2024-11-05T13:00:01.276+0000] {subprocess.py:93} INFO - Runtime Error
[2024-11-05T13:00:01.277+0000] {subprocess.py:93} INFO -   The profile 'adventureworks' does not have a target named 'dev'. The valid target names for this profile are:
[2024-11-05T13:00:01.279+0000] {subprocess.py:93} INFO -    - postgres
[2024-11-05T13:00:04.821+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-05T13:00:04.869+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:00:04.906+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_workflow_orchestration, task_id=transform.person.seed.adventureworks.address, run_id=manual__2024-11-05T12:51:34.487256+00:00, execution_date=20241105T125134, start_date=20241105T125939, end_date=20241105T130004
[2024-11-05T13:00:05.000+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:00:05.001+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task transform.person.seed.adventureworks.address (Bash command failed. The command returned a non-zero exit code 2.; 553)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-05T13:00:05.215+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T13:00:05.299+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:00:05.311+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
