[2024-11-05T13:52:01.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:52:01.199+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:59.775977+00:00 [queued]>
[2024-11-05T13:52:01.211+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:59.775977+00:00 [queued]>
[2024-11-05T13:52:01.211+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T13:52:01.229+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_docs_serve> on 2024-11-05 13:51:59.775977+00:00
[2024-11-05T13:52:01.235+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=521) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:52:01.236+0000] {standard_task_runner.py:72} INFO - Started process 522 to run task
[2024-11-05T13:52:01.237+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_docs_serve_dag', 'dbt_docs_serve', 'manual__2024-11-05T13:51:59.775977+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/dbt_docs_serve_dag.py', '--cfg-path', '/tmp/tmpy8zhgvry']
[2024-11-05T13:52:01.239+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask dbt_docs_serve
[2024-11-05T13:52:01.301+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_docs_serve_dag.dbt_docs_serve manual__2024-11-05T13:51:59.775977+00:00 [running]> on host bbd20199defe
[2024-11-05T13:52:01.423+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_docs_serve_dag' AIRFLOW_CTX_TASK_ID='dbt_docs_serve' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T13:51:59.775977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T13:51:59.775977+00:00'
[2024-11-05T13:52:01.424+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:52:01.451+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T13:52:01.452+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/dbt && nohup dbt docs serve --profiles-dir /root/.dbt --port 8001 &']
[2024-11-05T13:52:01.465+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T13:52:05.195+0000] {subprocess.py:93} INFO - Usage: dbt docs serve [OPTIONS]
[2024-11-05T13:52:05.195+0000] {subprocess.py:93} INFO - Try 'dbt docs serve -h' for help.
[2024-11-05T13:52:05.196+0000] {subprocess.py:93} INFO - 
[2024-11-05T13:52:05.196+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/root/.dbt' does not exist.
[2024-11-05T13:52:05.512+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-05T13:52:05.547+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:52:05.547+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_docs_serve_dag, task_id=dbt_docs_serve, run_id=manual__2024-11-05T13:51:59.775977+00:00, execution_date=20241105T135159, start_date=20241105T135201, end_date=20241105T135205
[2024-11-05T13:52:05.600+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T13:52:05.637+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:52:05.640+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
